version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geospatial_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: site_readiness
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgis_data:
